###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.2"
services:

    # memcached:
    #   image: memcached:alpine
    #   container_name: local-dev-memcached

    # redis:
    #   image: redis:alpine
    #   container_name: local-dev-redis

    webserver:
      image: nginx:alpine
      container_name: local-dev-webserver
      working_dir: /application
      volumes:
          - ~/Sites:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    webserver-apache:
      image: webdevops/php-apache-dev:alpine-php7
      container_name: local-dev-webserver-apache
      working_dir: /app
      volumes:
          - ~/Sites:/app

    php-fpm:
      build: phpdocker/php-fpm
      container_name: local-dev-php72-fpm
      working_dir: /application
      volumes:
        - ~/Sites:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
